- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.1
  hooks:
  - id: flake8
    entry: flake8 --max-line-length 88 # same as the setting of black
    additional_dependencies: [flake8-bugbear]

# type check
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.790
  hooks:
    - id: mypy
      args: [--no-strict-optional, --ignore-missing-imports]
      # additional_dependencies: [tokenize-rt==3.2.0]

- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python3

- repo: https://github.com/pycqa/isort
  rev: 5.5.2
  hooks:
    - id: isort

# commit cannot be done when cyclomatic complexity is more than 10.
- repo: local
  hooks:
    - id: lizard
      name: lizard
      entry: lizard -C 10
      language: python
      types: [python]
      exclude: ^test_.*$
